### PR TITLE
bug(ui): remove duplicate `Add Domain` button from update-domain component

### LINKED ISSUE #368: bug: duplicate add domain btn on settings/domain page
**Describe the bug**

There is a duplicate Add Domain btn appearing on the background whenever the Add Domain modal pops up. You can refer to the UI below, marked red region is where the duplicate btn appear. Additional context are provided below. 

**To Reproduce**
1. Login as Admin user
2. Click on Setting on the sidebar menu
3. Click on Domains on the sidebar sub menu
4. Click on the Add Domain btn
5. You will see this misbehavior

**Expected behavior**

No extra btn to be previewed on the modal popping up.

**Screenshots**

Image

Image

**Additional context**
- Browser: Chrome
- Operating System: macOS
- Screen Resolution: 1920x1080
- Language: en-GB
- Timezone: Asia/Calcutta
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36

### PR DESCRIPTION
**Pull request by Raj-G07**
- Fixes #368

## Summary by CodeRabbit

- **Refactor**
  - The Update Domain dialog no longer includes its own “Add” trigger button; opening is now controlled by parent views via existing controls.
  - Users will open the dialog from page-level actions rather than an in-component button.
  - Dialog behavior for add vs. edit remains unchanged: titles, validation, and submission flow are preserved.
  - No changes to public props or visible copy.

### CODE REVIEW

File: view/app/settings/domains/components/update-domain.tsx [hunk 1]
```diff
@@ -81,11 +81,6 @@ function UpdateDomainDialog({ open, setOpen, id, data }: UpdateDomainDialogProps
 
   return (
     <Dialog open={open} onOpenChange={setOpen}>
-      {!id && (
-        <DialogTrigger asChild>
-          <Button variant="outline">{t('settings.domains.update.addButton')}</Button>
-        </DialogTrigger>
-      )}
```
Comment (zhravan) [inline view/app/settings/domains/components/update-domain.tsx:88]: Nice catch!! 🙌🏻 

@Raj-G07: Can you remove the import for `DialogTrigger` since it is not used anywhere within the file?

LGTM.

---

Thank you so much your time and contribution towards the project! Really appreciate your efforts!! 🥇  

Look forward to more contributions!

Happy Learning!

---

PS: If you liked the project, consider starring ⭐ the project

**Review by zhravan — CHANGES_REQUESTED** [review]

**Review by zhravan — APPROVED** [review]

**Comment by Raj-G07** [comment]
@raghavyuva , @zhravan Thanks for reviewing and merging it !
